version: '3.8'

services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9500:9500"  # Exposing backend1 on port 9500
    networks:
      - loan-calculator-network

  backend2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9501:9500"  # Exposing backend2 on port 9501 (internal port 9500)
    networks:
      - loan-calculator-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Expose Nginx to the host's port 80
    networks:
      - loan-calculator-network

networks:
  loan-calculator-network:
    driver: bridge
