name: CI/CD Pipeline for Loan Calculator (Docker)

on:
  push:
    branches:
      - main
      - steve

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        run: |
          docker --version

      # Step 3: Build Docker image for backend
      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      # Step 4: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker-compose push

      # Step 6: Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/sync \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"serviceId": "your-render-service-id"}'

      # Step 7: Run Docker containers using Docker Compose
      - name: Run Docker containers
        run: |
          docker-compose up -d
