name: CI

on:
  push:
    branches:
      - steve
      - main
  pull_request:
    branches:
      - steve
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version  # Verify installation

      - name: Run Maven Build (skip tests)
        run: |
          mvn clean package -DskipTests  # Skip tests during build

      - name: Build Docker Images
        run: docker-compose -f docker-compose.yml build

      - name: Start Services
        run: docker-compose -f docker-compose.yml up -d

      - name: Tear Down Services
        if: always()
        run: docker-compose -f docker-compose.yml down
