name: CI/CD Pipeline for Loan Calculator (Docker)

on:
  push:
    branches:
      - main
      - steve

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        run: |
          docker --version

      # Step 3: Build Docker image for backend
      - name: Build Docker image
        run: |
          docker build -t loan-calculator .

      # Step 4: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker tag loan-calculator otizaaa/loan-calculator:latest
          docker push otizaaa/loan-calculator:latest

      # Step 6: Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/sync \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"serviceId": "your-render-service-id"}'

      # Step 7: Create Docker network
      - name: Create Docker network
        run: |
          docker network create loan-calculator-network || echo "Network already exists"

      # Step 8: Run Docker container for backend1
      - name: Run Docker container backend1
        run: |
          docker run -d \
            --network loan-calculator-network \
            -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            -p 9500:9500 \
            --name backend1 \
            loan-calculator

      # Step 9: Run Docker container for backend2
      - name: Run Docker container backend2
        run: |
          docker run -d \
            --network loan-calculator-network \
            -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            -p 9501:9500 \
            --name backend2 \
            loan-calculator

      # Step 10: Run Docker container for NGINX
      - name: Run Docker container for NGINX
        run: |
          docker run -d \
            --network loan-calculator-network \
            -p 80:80 \
            --name nginx \
            nginx:alpine

